config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items, only: [:new, :create, :update]
  resources :carts, only: [:new, :create, :update, :show]
  resources :orders, only: [:new, :create, :index, :show]
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :categories
  resources :users, only: [:update]
end

app/views/partials/_exception.html.erb
<div class="card-product-detail">
    <div class="exception-container-image">
        <%= link_to image_tag("page-not-found.png", class:"icon-exception"), root_path %>
    </div>
    <div class="exception-container-text">
        <p class="exception-text">Oops! Something Went Wrong</p>
    </div>
</div>

app/views/partials/_footer.html.erb
<div class="footer-clean">
        <footer>
            <div class="container-footer">
                <div class="container-items-footer">
                    <div class="item margin-top-footer">
                        <h3>Brands</h3>
                        <ul>
                            <li><a href="#">Adidas</a></li>
                            <li><a href="#">Puma</a></li>
                            <li><a href="#">Reebok</a></li>
                            <li><a href="#">Nike</a></li>
                        </ul>
                    </div>
                    <div class="item margin-top-footer">
                        <h3>Company</h3>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Find a Store</a></li>
                            <li><a href="#">Rules and Terms</a></li>
                            <li><a href="#">Sitemap</a></li>
                            <li><a href="#">Career</a></li>
                        </ul>
                    </div>
                    <div class="item margin-top-footer">
                        <h3>Help</h3>
                        <ul>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Money Refund</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Shipping Info</a></li>
                            <li><a href="#">Open Dispute</a></li>
                        </ul>
                    </div>
                    <div class="item margin-top-footer">
                        <h3>Account</h3>
                        <ul>
                            <li><a href="#">Login</a></li>
                            <li><a href="#">Register</a></li>
                            <li><a href="#">Account Setting</a></li>
                            <li><a href="#">My Orders</a></li>
                        </ul>
                    </div>
                     <div class="item margin-top-footer">
                        <h3>Social</h3>
                        <ul>
                            <li><%= image_tag("icon-facebook.png", :class => "icon-facebook") %><a class="social" href="#">Facebook</a></li>
                            <li><%= image_tag("icon-twitter.png", :class => "icon-twitter") %><a class="social" href="#">Twitter</a></li>
                            <li><%= image_tag("icon-instagram.png", :class => "icon-facebook") %><a class="social" href="#">Instagram</a></li>
                            <li><%= image_tag("icon-youtube.png", :class => "icon-youtube") %><a class="social" href="#">Youtube</a></li>
                        </ul>
                    </div>
                    <div class="col-12 hr-footer "></div>
                    <div class="under-hr-footer">
                        <div class="col-sm-4 col-md-4 col-4">
                            <h4 class="container-footer-uno">© 2019 Pixsellz. All rights reserved.</h4>
                        </div>
                        <div class="col-sm-4 col-md-4 col-4 cont-2-footer">
                            <h4 class="container-footer-dos info">info@pixsellz.io</h4>
                            <h4 class="container-footer-dos">879-332-9375</h4>
                            <h4 class="container-footer-dos">456 Hagenes Gardens Suite 808</h4>
                        </div>
                        <div class="col-sm-3 col-md-3 col-2 icons-pay-methods">
                            <div class="icon-footer american-express-margin">
                             <%= image_tag("logo-american-express@3x.png", :class => "icon-american-express icon-footer-pay-methods") %>
                            </div>
                            <div class="icon-footer">
                             <%= image_tag("logo-mastercard.png", :class => "icon-mastercard icon-footer-pay-methods") %>
                            </div>
                            <div class="icon-footer">
                             <%= image_tag("logo-paypal.png", :class => "icon-paypal icon-footer-pay-methods") %>
                            </div>
                            <div class="icon-footer">
                                <%= image_tag("logo-visa.png", :class => "icon-visa icon-footer-pay-methods") %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

app/views/partials/_nav.html.erb
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <nav class="navbar d-flex justify-content-between">
      <li class="nav-item" style="list-style-type: none;">
          <%= link_to image_tag("logoheader3x.png", class:"nav-link logo-header"), root_path %>
      </li>
      <div class="nav-item none-display-searchbar" style="list-style-type: none;">
          <%= text_field_tag(:search, params[:search], placeholder: "Search", :class =>"searchbar") %>
          <%= image_submit_tag("icon-sarch@3x.png", class: "btn search-icon") %>
      </div>
      <% if user_signed_in? %>
        <li class="nav-item" style="list-style-type: none;">
            <div class= "btn btn-primary-my-cart" >
              <%= link_to "My Cart", cart_path(current_user.cart), method: :get, class: "my-cart-text-style" %>
              <p class="number"><%= current_user.cart.calculate_quantity %></p>
            </div>
            <div class="nav-item subnav" style="list-style-type: none;">
                <div class="account">
                  <p><%= link_to image_tag("group-3@3x.png", class:"icon-menu") %>
                  <p>My account</p>
                </div>
                <ul class="subnav-content nav">
                  <li class="element-menu element-menu-line"><%= link_to "My orders", orders_path(@order) %></li>
                  <li class="element-menu"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                </ul>
            </div>
        </li>
      <% else %>
          <li class="nav-item" style="list-style-type: none;">
            <%= link_to "Login", new_user_session_path, class:"btn btn-primary-login" %>
          </li>
          <li class="nav-item" style="list-style-type: none;">
            <%= link_to "Sign up", new_user_registration_path, class:"btn btn-primary-sign-up" %>
          </li>
          <li class="nav-item" style="list-style-type: none;">
            <div class= "btn btn-primary-my-cart"
              <%= link_to "My Cart", new_user_registration_path %>
              <p class="number">0</p>
            </div>
          </li>
        <%end%>
    </nav>
    <div class="topnav">
      <div class="container-logo-hamburger">
        <%= link_to image_tag("logo-loopcommerce@3x.png", class:"active-hamburger") %>
      </div>
      <div class="searchbar-hamburger" style="list-style-type: none;">
        <%= text_field_tag(:search, params[:search], placeholder: "Search", :class =>"searchbar") %>
        <%= image_submit_tag("icon-sarch@3x.png", class: "btn search-icon") %>
      </div>
      <% if user_signed_in? %>
        <div class="hr-hamburger" id="myLinks">
          <a><%= link_to "My orders", orders_path, method: :delete, class:"hamburger-menu" %></a>
          <a><%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"hamburger-menu" %></a>
        </div>
      <% else %>
        <div class="hr-hamburger" id="myLinks">
          <a><%= link_to "Login", new_user_session_path, class:"hamburger-menu" %></a>
          <a><%= link_to "Sign up", new_user_registration_path, class:"hamburger-menu" %></a>
          <a><%= link_to "My cart", destroy_user_session_path, method: :delete, class:"hamburger-menu" %></a>
        </div>
      <%end%>
      <div class="icon-hamburger">
         <a href="javascript:void(0);" class="icon" id="icon-menu">
           <i class="fa fa-bars"></i>
          </a>
      </div>      
  </div>
  <%= javascript_pack_tag 'hamburger' %>