config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items, only: [:new, :create, :update]
  resources :carts, only: [:new, :create, :update, :show]
  resources :orders, only: [:new, :create, :index, :show]
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :categories
  resources :users, only: [:update]
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    validates_presence_of :phone, :address
    has_many :order_items

    def calculate_total
        total_amount = 0
        self.order_items.each do |item|
            total_amount += item.total_order_item
        end
        self.total = total_amount
        self.save!
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_cart, only: [:create, :new]

    def index
        if defined?(current_user) && !current_user.nil?
            @orders = current_user.orders
        else
            return render_error(:user_must_exist, :bad_request)
        end
    end

    def new
        @order = Order.new
    end

    def create
        if @order = Order.create!(order_params.merge(user: current_user))
            @cart.line_items.each do |item|
                @order.order_items.create!(
                    product_id: item.product_id,
                    quantity: item.quantity,
                    price: item.product.price
                )
                item.delete
            end
        end
        @order.calculate_total
        redirect_to orders_path
    end

    def show
        if defined?(current_user) && !current_user.nil?
            order
        else
            return render_error(:user_must_exist, :bad_request)
        end
    end

    private

    def order
        @order ||= Order.find(params[:id])
    end

    def render_error(error, status)
        render_errors(I18n.t("errors.#{error}"), status)
    end

    def order_params
        params.require(:order).permit(:address, :phone, :user_id)
    end
end

app/views/orders/_order.html.erb
<div>
    <li class="cart-rows-content bold-cart-row"><%= @order.id %> </li>
    <li class="cart-rows-content bold-cart-row"><%= @order.created_at.strftime("%Y-%m-%d") %> </li>
    <li class="order-rows-content-total"><%= number_to_currency(@order.total) %></li>
    <%= link_to image_tag("eye.png", class:"view-order-icon"), order_path(@order.id) %>
    <div class="col-12 hr-cart "></div>
</div>

app/views/orders/index.html.erb
<div class="cart-screen">
    <div class="carrito-title">
        <h2>Orders</h2>
    </div>
    <div class="card-product-detail-cart">
            <div class="line_items">
                <% if @orders.any? %>
                    <div class="cart-rows-container">
                        <li class="cart-rows cart-rows-id">ID</li>
                        <li class="cart-rows cart-rows-date">DATE</li>
                        <li class="cart-rows cart-rows-amount">AMOUNT</li>
                        <li class="cart-rows cart-rows-action">ACTIONS</li>
                    </div>
                    <% @orders.each do |orders| %>
                        <% @order = orders%>
                        <%= render partial: "orders/order", orders: @order %>
                    <% end %>
                <% else %>
                    <p class="default-cart-title">No tienes ninguna order</p>
                    <p class="default-cart-text">Añade productos a tu carrito para poder crear una orden de compra.</p>
                    <%= render template: "line_items/nolineitem" %>
                <% end %>
            </div>
    </div>
</div>

app/views/orders/new.html.erb
<div class="carrito-title">
    <h2>Confirmación de orden</h2>
</div>
<div class="card-product-detail-cart">
    <%= form_for @order, url: orders_path(@order), method: :post do |f| %>
        <div class="container-input-cart">
            <div class="container-input-uno">
                <%= f.label :address, "Address", :class => "label-email" %>
                <%= f.text_field :address, placeholder: "Type your address", :class => "Rectangle-6" %>
            </div>
            <div class="container-input-uno">
                <%= f.label :phone, "Phone", :class => "label-email" %>
                <%= f.text_field :phone, placeholder: "Type your phone", :class => "Rectangle-6" %>
            </div>
            <div class="total-cart-in-card">
              <h1 class="total-cart-in-card"><%= number_to_currency(@cart.total) %></h1>
            </div>
            <div class="buy-now-cart">
                <li class="nav-item" style="list-style-type: none;">
                    <%= f.submit "Buy now", class: "btn btn-primary-login btn-buy-now-cart" %>
                </li>
            </div>
        </div>
    <% end %>
</div>

app/views/orders/show.html.erb
<div class="cart-screen">
    <div class="carrito-title">
        <h2>Your order</h2>
    </div>
    <div class="card-product-detail-cart">
            <div class="cart-rows-container">
                <li class="cart-rows my-order-cart-rows">ID</li>
                <li class="cart-rows my-order-cart-rows">PHONE</li>
                <li class="cart-rows my-order-cart-rows address-cart-row">ADDRESS</li>
                <li class="cart-rows my-order-cart-rows">PRODUCT</li>
                <li class="cart-rows cart-rows-action quantity-cart-row">QUANTITY</li>
            </div>
            <div class="line_items content-my-order">
                    <li class="cart-rows-content bold-cart-row my-order-cart-content id-cart-row"><%= @order.id %> </li>
                    <li class="cart-rows-content my-order-cart-content"><%= @order.phone %> </li>
                    <li class="cart-rows-content my-order-cart-content address-cart-order"><%= @order.address %> </li>
                <div class="cart-row-content-price-name">
                    <% @order.order_items.each do |order| %>
                        <div class="container-name-price-my-order">
                            <div class="container-name-my-order">
                                <li class="my-orders-content-style"><%= order.product.name %> </li>
                            </div>
                            <div class="container-price-my-order">
                                <li class="bold-cart-row my-orders-content-style"><%= number_to_currency((order.price * order.quantity)) %> </li>
                            </div>
                        </div>
                    <% end %>
                    <div class="total-cart-in-card-my-order">
                        <h1 class="total-cart-in-card"><%= number_to_currency(@order.total) %></h1>
                    </div>
                </div>
            </div>
    </div>
</div>