config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items, only: [:new, :create, :update]
  resources :carts, only: [:new, :create, :update, :show]
  resources :orders, only: [:new, :create, :index, :show]
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :categories
  resources :users, only: [:update]
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :user
    validates :total, presence: true

    def update_total
        total_amount = 0
        line_items.each do |line_item|
            total_amount += line_item.total
        end
        self.total = total_amount
        self.save!
    end

    def calculate_quantity
        total_quantity = 0
        line_items.each do |line_item|
            total_quantity += line_item.quantity
        end
        total_quantity
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show]

  def show
  end

end

app/views/carts/show.html.erb
<div class="cart-screen">
    <div class="carrito-title">
        <h2>Carrito</h2>
    </div>
    <div class="card-product-detail-cart">
        <% if @cart.line_items.any? %>
            <div class="cart-rows-container">
                <li class="cart-rows cart-rows-product">PRODUCTO</li>
                <li class="cart-rows cart-rows-quantity">CANTIDAD</li>
                <li class="cart-rows cart-rows-price">PRECIO</li>
                <li class="cart-rows">TOTAL</li>
            </div>
            <div class="line_items" data-lineitems="<%= @cart.line_items.pluck(:id).join(', ') %>">
                <% @cart.line_items.each do |item| %>
                <% @item = item%>
                <%= render partial: "line_items/lineitem", item: @item %>
             <% end %>
            </div>

            <div class="total-cart-in-card">
                <h1 class="total-cart-in-card"><%= number_to_currency(@cart.total) %></h1>
            </div>
            <div class="buy-now-cart">
                <li class="nav-item" style="list-style-type: none;">
                    <%= link_to "Buy Now", new_order_path, class:"btn btn-primary-login btn-buy-now-cart" %>
                </li>
            </div>
        <% else %>
            <p class="default-cart-title">Tu carrito está vacío</p>
            <p class="default-cart-text">Añade productos a tu carrito para poder crear una orden de compra.</p>
            <%= render template: "line_items/nolineitem" %>
        <% end %>
    </div>
</div>
<%= javascript_pack_tag 'cart-counter'%>