config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items, only: [:new, :create, :update]
  resources :carts, only: [:new, :create, :update, :show]
  resources :orders, only: [:new, :create, :index, :show]
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :categories
  resources :users, only: [:update]
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_one_attached :image
  include Pagy::Frontend
  validates_presence_of :price, :name
  has_many :line_items, dependent: :destroy
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def show
    @product = Product.find params[:id]
    @product_line_item = cart.line_items.find_by(product: @product) if current_user
  end

  private

  def cart
    current_user.cart
  end
end

app/views/products/index.html.erb
<p class="text-arrivals">New Arrivals</p>
<div class="container-products">
    <% @products.each do |product| %>
        <% if current_user %>
            <%= link_to product_path(product.id) do %>
                <div class="products-home">
                    <%= image_tag(url_for(product.image), :class => "img-products") %>
                    <div class="line-product"></div>
                    <p class="title-products font-styles-products"><%= label_tag (product.name)%></p>
                    <p class="price-products"><%= number_to_currency(product.price)%></p>
                    <%= link_to "ADD TO CART", line_items_path(product_id: product), class:"btn btn-primary-login add-to-cart-button", method: :post %>
                </div>
            <% end %>
        <% else %>
            <%= link_to product_path(product.id) do %>
                <div class="products-home">
                    <%= image_tag(url_for(product.image), :class => "img-products") %>
                    <div class="line-product"></div>
                    <p class="title-products font-styles-products"><%= label_tag (product.name)%></p>
                    <p class="price-products"><%= number_to_currency(product.price)%></p>
                    <%= link_to "ADD TO CART", new_user_session_path, class:"btn btn-primary-login add-to-cart-button", method: :post %>
                </div>
            <% end %>
        <% end %>
    <%end%>
</div>
<div class="pagy">
<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/products/show.html.erb
  <div class="card-product-detail">
    <div class="card-container-one">
        <%= image_tag(url_for(@product.image), :class => "card-product-detail-image")%>
    </div>
    <div class="card-container-two">
        <p class= "card-product-detail-title"><%=@product.name%></p>
        <p class= "card-product-detail-price">$<%=@product.price%></p><p class="per-unit-card-product">/ per unit</p>
        <p class="card-product-text">Safely that been the to win of pane, its the later thoroughly, all it the he only the of slid choose flows the instead in heard them.</p>
        <p class="card-product-quantity">Quantity</p>
        
        <% if @product_line_item %>
            <%= form_for @product_line_item, url: line_item_path(@product_line_item), method: :put do |f| %>
              <div class="quantity">
                <button class="btn minus-btn" type="button">-</button>
                <%= f.text_field :quantity, value: @product_line_item.quantity, class: "quantity-input" %>
                <button class="btn plus-btn" type="button">+</button>
                <li class="nav-item" style="list-style-type: none;">
                  <%= f.submit "Add to Cart", class: "btn btn-add-to-cart" %>
                  <%= link_to image_tag("carrito-compras-icon.png", class:"add-to-cart-icon") %>
                </li>
              </div>
                <li class="nav-item" style="list-style-type: none;">
                  <%= f.submit name: "type",value: "Buy now", class: "btn btn-primary-login btn-buy-now" %>
                </li>
            <% end %>
        <% else %>
            <% if current_user %>
              <%= form_for LineItem.new(product: @product), url: line_items_path(product_id: @product), method: :post do |f| %>
                  <div class="quantity">
                    <button class="btn minus-btn" type="button">-</button>
                    <%= f.text_field :quantity, value: 0, class: "quantity-input" %>
                    <button class="btn plus-btn" type="button">+</button>
                    <li class="nav-item" style="list-style-type: none;">
                      <%= f.submit "Add to Cart", class: "btn btn-add-to-cart" %>
                      <%= link_to image_tag("carrito-compras-icon.png", class:"add-to-cart-icon") %>
                    </li>
                  </div>
                   <li class="nav-item" style="list-style-type: none;">
                      <%= f.submit name: "type", value: "Buy now", class: "btn btn-primary-login btn-buy-now" %>
                    </li>
              <% end %>
            <% else %>
                  <div class="quantity">
                    <button class="btn minus-btn" type="button">-</button>
                    <%= text_field_tag(:line_item_quantity, "1", class: "quantity-input") %>
                    <button class="btn plus-btn" type="button">+</button>
                    <li class="nav-item" style="list-style-type: none;">
                      <%= link_to "Add to Cart", new_user_session_path, class:"btn btn-add-to-cart" %>
                      <%= link_to image_tag("carrito-compras-icon.png", class:"add-to-cart-icon") %>
                    </li>
                  </div>
                  <li class="nav-item" style="list-style-type: none;">
                    <%= link_to "Buy Now", new_user_session_path, class:"btn btn-primary-login btn-buy-now" %>
                  </li>
            <% end %>
        <% end %>
          <li class="nav-item" style="list-style-type: none;">

    </div>
</div>
<%= javascript_pack_tag 'counterproduct' %>
<%= render "partials/footer" %>